remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Title of your site
title: Datenbank Stahlproben

# URL of your site (should be the URL where your site is hosted)
url: "https://stahlprobe.github.io/probe"

# Theme settings
#theme: minima
